### ISSUE TITLE
Kapacitor alerts not displayed if tick is not human readable

### ISSUE THREAD

**Issue by DarthSidious-DBA** [influxdata/kapacitor#2426]
@russorat 

I have an alert that is saved in "not human readable":
![image](https://user-images.githubusercontent.com/72392361/97981189-31c0f900-1dd2-11eb-9a8a-42169f639cdc.png)

I make this alert to be raised:
![image](https://user-images.githubusercontent.com/72392361/97981331-6765e200-1dd2-11eb-8746-9150899559e1.png)

I also make another (human readable) alert to be raised:
![image](https://user-images.githubusercontent.com/72392361/97981489-ab58e700-1dd2-11eb-9feb-6c1d2640ff86.png)

Both alerts raised successfully but only one is shown in alert history:
![image](https://user-images.githubusercontent.com/72392361/97981763-130f3200-1dd3-11eb-9506-bfbe9aa269e6.png)

As we forward the kapacitor alerts to another tool we can see that the not human readable tick script is working fine:
![image](https://user-images.githubusercontent.com/72392361/97981983-64b7bc80-1dd3-11eb-94cb-02a990fe1e6e.png)

Thanks in advance

**Comment by russorat** [comment]
I believe this is addressed here: https://github.com/influxdata/chronograf/issues/4304

chronograf 1.8.8 should be coming soon.

**Comment by DarthSidious-DBA** [comment]
@russorat 
In your mentioned issue it is only regarding the management of tick scripts.

I am talking about log history. Those alerts are not displayed at all if ok, warning or critical is raised.

**Comment by a-vogel-tappert** [comment]
@russorat 
We are still not able to view alerts in UI. 
But alerts are available in kapacitor.db file (using cat command).

Any activity to fix that issue in progress ?
Thx in advance.
